CC = gcc
TARGETS = build-problem11 build-problem12
EXE = problem11 problem12

all: $(TARGETS)

build-problem11:
	$(CC) problem11.c -o problem11
build-problem12:
	$(CC) problem12.c -o problem12
clean:
	rm $(EXE)
