CC = gcc
TARGETS = build-problem11 build-problem12 build-problem13
EXE = problem11 problem12 problem13

all: $(TARGETS)

build-problem11:
	$(CC) problem11.c -o problem11
build-problem12:
	$(CC) problem12.c -o problem12
build-problem13:
	$(CC) problem13.c -o problem13
clean:
	rm $(EXE)
